name: Node.js CI

on:
  push:
    branches: [ no-branch ]
  pull_request:
    branches: [ no-branch ]
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: List S3 Buckets
      run: aws s3api list-buckets