name: Upload artifact

on: 
  push:
    branches:
      - "no-branch"

env:
  ARTIFACT_NAME: my_artifact

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .