name: Multi-job workflow

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-lates
    steps:
    - run: date
  windows:
    runs-on: windows-lates
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  depends:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
    - run: date
