name: Multi-job workflow

on: push

jobs:
  multi-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - run: date
        
  depends:
    runs-on: ubuntu-latest
    needs: [multi-os]
    steps:
    - run: date
