name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  WORKFLOW_VAR: "my workflow env var"
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
      JOB_VAR: "my job env var"

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - name: "Configure AWS Credentials"
      # You may pin to the exact commit or the version.
      # uses: aws-actions/configure-aws-credentials@d2221ce3c7101a35ff049cc8fe652f5c9a64372d
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
        aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ID }}
        # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 