name: Node.js CI

on:
  push:
    branches: [ no-branch ]
  pull_request:
    branches: [ no-branch ]
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12

    steps:
    - uses: actions/checkout@v2
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: local-library
        path: .
        if-no-files-found: error
