name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12

    steps:
    - uses: actions/checkout@v2
      
    # - name: Use Node.js ${{ env.NODE_VERSION }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}
    # - run: npm ci

    - name: Zip repo files
      run: | #fix the folder to zip
        cd ..
        tar -zcvf local-library.tar.gz local-library/

    - run: |
        cd ..
        ls
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: local-library
        path: "**/local-library.tar.gz"
        if-no-files-found: error
